annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.0.8
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
home: https://github.com/distorhead/helm-chart-example
keywords:
- redis
- keyvalue
- database
name: redis
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/redis
version: 17.6.0
